set -e

BOOST_VERSION="{{__VERSION__}}"
ARCHITECTURE="{{__ARCHITECTURE__}}"

if [ -z ${AGENT_TOOLSDIRECTORY+x} ]; then
    # No AGENT_TOOLSDIRECTORY on GitHub images
    TOOLCACHE_ROOT=$RUNNER_TOOL_CACHE
else
    TOOLCACHE_ROOT=$AGENT_TOOLSDIRECTORY
fi

BOOST_TOOLCACHE_PATH=$TOOLCACHE_ROOT/boost
BOOST_TOOLCACHE_VERSION_PATH=$BOOST_TOOLCACHE_PATH/$BOOST_VERSION
BOOST_TOOLCACHE_VERSION_ARCH_PATH=$BOOST_TOOLCACHE_VERSION_PATH/$ARCHITECTURE

echo "Check if Boost hostedtoolcache folder exist..."
if [ ! -d $BOOST_TOOLCACHE_PATH ]; then
    mkdir -p $BOOST_TOOLCACHE_PATH
fi

echo "Delete Boost $BOOST_VERSION [$ARCHITECTURE] if installed"
rm -rf $BOOST_TOOLCACHE_VERSION_ARCH_PATH

echo "Create Boost $BOOST_VERSION [$ARCHITECTURE] folder"
mkdir -p $BOOST_TOOLCACHE_VERSION_ARCH_PATH

echo "Copy Boost binaries to hostedtoolcache folder"
cp -R ./* $BOOST_TOOLCACHE_VERSION_ARCH_PATH
rm $BOOST_TOOLCACHE_VERSION_ARCH_PATH/setup.sh

echo "Create complete file"
touch $BOOST_TOOLCACHE_VERSION_PATH/$ARCHITECTURE.complete
